// import { Inter } from 'next/font/google';
import '../_styles/globals.css';
import 'react-tooltip/dist/react-tooltip.css';
import '../_styles/SegoeUI.css';

import HomeProvider from 'context/Provider';
import type { Metadata } from 'next';
import React from 'react';

import Footer from '../_components/Footer';

export const metadata: Metadata = {
  title: 'Grey Matter',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  }
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang={params.locale}>
      <body>
        <HomeProvider>
          {children}
          <Footer />
        </HomeProvider>
      </body>
    </html>
  );
}
