// import { Inter } from 'next/font/google';
import '../_styles/globals.css';
import 'react-tooltip/dist/react-tooltip.css';
import '../_styles/SegoeUI.css';

import Footer from 'app/_components/Footer';
import HomeProvider from 'context/Provider';
import { getClient } from 'lib/sanityClient';
import { getFooter, getSiteSettings } from 'lib/sanityFetch';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Grey Matter',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: {
    locale: string;
  }
};

export default async function RootLayout({ children, params: { locale } }: RootLayoutProps) {
   const client = getClient();
  const footer = await getFooter(client, locale);
  const { logo } = await getSiteSettings(client);

  return (
    <html lang={locale}>
      <body>
        <HomeProvider>
          {children}
        </HomeProvider>
        <Footer locale={locale} data={footer} greymatterLogo={logo} />
      </body>
    </html>
  );
}
